# Generated by Django 2.0.7 on 2019-02-19 14:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('renter', '0003_rentaddres'),
        ('classification_list', '0004_auto_20190219_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='геометрия')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'список выделов',
                'verbose_name': 'выдел',
            },
        ),
        migrations.CreateModel(
            name='DistrForestKeys',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('df_names', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='геометрия')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'УЛВы',
                'verbose_name': 'УЛВ',
            },
        ),
        migrations.CreateModel(
            name='Fca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ar_fca', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fell_form', models.TextField(blank=True, null=True)),
                ('fell_type', models.IntegerField(blank=True, null=True)),
                ('main_type', models.IntegerField(blank=True, null=True)),
                ('vol_zag', models.FloatField(blank=True, null=True)),
                ('biz_type', models.CharField(blank=True, max_length=50, null=True)),
                ('expl_ar', models.FloatField(blank=True, null=True)),
                ('cel_nazn', models.IntegerField(blank=True, null=True)),
                ('cat_zas', models.IntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('video_cat', models.TextField(blank=True, null=True)),
                ('num_allot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cutarea.Allotment')),
                ('num_of_agree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='renter.Agreement')),
                ('renter_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='renter.Renters')),
                ('sortiment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.ForestSort', verbose_name='cортиментный состав')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.SubjectRf')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'лесосеки',
                'verbose_name': 'лесосека',
            },
        ),
        migrations.CreateModel(
            name='FcaPhoto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('point_no', models.IntegerField(blank=True, null=True)),
                ('coords', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_no', models.IntegerField(blank=True, null=True)),
                ('ext', models.CharField(blank=True, max_length=10, null=True)),
                ('ref', models.TextField(blank=True, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('id_fca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cutarea.Fca')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'фотографии',
                'verbose_name': 'фото',
            },
        ),
        migrations.CreateModel(
            name='FcaUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_drew', models.FloatField(blank=True, null=True)),
                ('fca_res', models.SmallIntegerField(blank=True, null=True)),
                ('vol_res', models.FloatField(blank=True, null=True)),
                ('ed_izm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.UnitMeas', verbose_name='единица измерения')),
                ('fell_form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.ShapeFelling', verbose_name='форма рубки')),
                ('fell_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.TypeFelling', verbose_name='вид рубки')),
                ('id_fca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cutarea.Fca')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.ForestKind', verbose_name='породный состав')),
                ('main_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.TypesForestry', verbose_name='тип хозяйства')),
            ],
        ),
        migrations.CreateModel(
            name='FcaWorks',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('wkod', models.SmallIntegerField(blank=True, null=True)),
                ('vol_drew', models.FloatField(blank=True, null=True)),
                ('fca_res', models.SmallIntegerField(blank=True, null=True)),
                ('vol_les', models.FloatField(blank=True, null=True)),
                ('act_name', models.SmallIntegerField(blank=True, null=True)),
                ('obj_type', models.SmallIntegerField(blank=True, null=True)),
                ('use_area', models.FloatField(blank=True, null=True)),
                ('indicator', models.SmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_report', models.DateField(blank=True, null=True)),
                ('ed_izm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.UnitMeas', verbose_name='единица измерения')),
                ('id_fca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cutarea.Fca')),
                ('sortiment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.ForestSort', verbose_name='cортиментный состав')),
                ('use_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.ForestUse', verbose_name='вид рубки')),
            ],
            options={
                'managed': True,
                'verbose_name': 'фактические работы',
            },
        ),
        migrations.CreateModel(
            name='ForestryKeys',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='геометрия')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'лесничества',
                'verbose_name': 'лесничество',
            },
        ),
        migrations.CreateModel(
            name='ForestSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_doc', models.CharField(blank=True, max_length=80, null=True)),
                ('date_doc', models.DateField(blank=True, null=True)),
                ('id_rr', models.IntegerField(blank=True, null=True)),
                ('name_gov', models.CharField(blank=True, max_length=80, null=True)),
                ('num_grd', models.CharField(blank=True, max_length=80, null=True)),
                ('date_grd', models.DateField(blank=True, null=True)),
                ('kud_number', models.CharField(blank=True, max_length=30, null=True)),
                ('num_glr', models.CharField(blank=True, max_length=30, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_stop', models.DateField(blank=True, null=True)),
                ('num_akt', models.CharField(blank=True, max_length=15, null=True)),
                ('date_akt', models.DateField(blank=True, null=True)),
                ('projects', models.IntegerField(blank=True, null=True)),
                ('num_kv', models.CharField(blank=True, max_length=10, null=True)),
                ('district_forestry', models.CharField(blank=True, max_length=50, null=True)),
                ('forestry', models.CharField(blank=True, max_length=80, null=True)),
                ('radio', models.SmallIntegerField(blank=True, null=True)),
                ('osn_pred_uch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.Osnovanie')),
                ('vid_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.Viddoc')),
            ],
            options={
                'managed': True,
                'verbose_name': 'договоры 2',
            },
        ),
        migrations.CreateModel(
            name='QartalKeys',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='геометрия')),
                ('district_forestry_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cutarea.DistrForestKeys')),
                ('forestry_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cutarea.ForestryKeys')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'кварталы',
                'verbose_name': 'квартал',
            },
        ),
        migrations.CreateModel(
            name='TractKeys',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tract_name', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='геометрия')),
                ('district_forestry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cutarea.DistrForestKeys')),
                ('forestry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cutarea.ForestryKeys')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'урочища',
                'verbose_name': 'урочище',
            },
        ),
        migrations.AddField(
            model_name='qartalkeys',
            name='tract_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cutarea.TractKeys'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='district_forestry_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cutarea.DistrForestKeys'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='forestry_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cutarea.ForestryKeys'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='num_kvr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cutarea.QartalKeys'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='tract_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cutarea.TractKeys'),
        ),
    ]
