# Generated by Django 2.0.7 on 2019-02-20 06:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutarea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='геометрия'),
        ),
        migrations.AlterField(
            model_name='distrforestkeys',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='геометрия'),
        ),
        migrations.AlterField(
            model_name='forestrykeys',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='геометрия'),
        ),
        migrations.AlterField(
            model_name='qartalkeys',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='геометрия'),
        ),
        migrations.AlterField(
            model_name='tractkeys',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='геометрия'),
        ),
    ]
