# Generated by Django 2.0.7 on 2019-02-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification_list', '0005_auto_20190220_1523'),
        ('cutarea', '0002_auto_20190220_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forestsite',
            name='osn_pred_uch',
        ),
        migrations.RemoveField(
            model_name='forestsite',
            name='vid_doc',
        ),
        migrations.RemoveField(
            model_name='tractkeys',
            name='district_forestry',
        ),
        migrations.RemoveField(
            model_name='tractkeys',
            name='forestry',
        ),
        migrations.AlterModelOptions(
            name='fcaworks',
            options={'managed': True, 'verbose_name': 'фактические работы', 'verbose_name_plural': 'фактические работы'},
        ),
        migrations.RenameField(
            model_name='fca',
            old_name='biz_type',
            new_name='num_fca',
        ),
        migrations.RenameField(
            model_name='fca',
            old_name='fell_form',
            new_name='uroch',
        ),
        migrations.RemoveField(
            model_name='allotment',
            name='district_forestry_id',
        ),
        migrations.RemoveField(
            model_name='allotment',
            name='forestry_id',
        ),
        migrations.RemoveField(
            model_name='allotment',
            name='tract_id',
        ),
        migrations.RemoveField(
            model_name='fca',
            name='fell_type',
        ),
        migrations.RemoveField(
            model_name='fca',
            name='main_type',
        ),
        migrations.RemoveField(
            model_name='fca',
            name='renter_name',
        ),
        migrations.RemoveField(
            model_name='fca',
            name='vol_zag',
        ),
        migrations.RemoveField(
            model_name='fcaphoto',
            name='coords',
        ),
        migrations.RemoveField(
            model_name='qartalkeys',
            name='forestry_id',
        ),
        migrations.RemoveField(
            model_name='qartalkeys',
            name='tract_id',
        ),
        migrations.AddField(
            model_name='distrforestkeys',
            name='forestry_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cutarea.ForestryKeys'),
        ),
        migrations.AddField(
            model_name='fcaworks',
            name='fell_form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.ShapeFelling', verbose_name='форма рубки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcaworks',
            name='fell_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.TypeFelling', verbose_name='вид рубки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcaworks',
            name='kind',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.ForestKind', verbose_name='вид рубки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcaworks',
            name='main_type',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fca',
            name='cat_zas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.ForestProtection', verbose_name='категория лесозащиты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fca',
            name='cel_nazn',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.ForestPurpose', verbose_name='целевое назначение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fcaworks',
            name='indicator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.Forestation', verbose_name='лесовосстановление'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ForestSite',
        ),
        migrations.DeleteModel(
            name='TractKeys',
        ),
    ]
