# Generated by Django 2.0.7 on 2019-02-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification_list', '0005_auto_20190220_1523'),
        ('cutarea', '0003_auto_20190220_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fca',
            name='sortiment',
        ),
        migrations.RemoveField(
            model_name='fcause',
            name='kind',
        ),
        migrations.AddField(
            model_name='fcause',
            name='sortiment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.ForestSort', verbose_name='cортиментный состав'),
            preserve_default=False,
        ),
    ]
