# Generated by Django 2.0.7 on 2019-02-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cutarea', '0004_auto_20190221_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcause',
            name='fell_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.ShapeFelling', verbose_name='вид рубки'),
        ),
        migrations.AlterField(
            model_name='fcause',
            name='fell_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.TypeFelling', verbose_name='форма рубки'),
        ),
    ]
