# Generated by Django 2.0.7 on 2019-02-26 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cutarea', '0006_auto_20190226_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcaworks',
            name='wkod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.ForestWorks', verbose_name='вид работ'),
        ),
    ]
