version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: docker/local.dockerfile
    restart: always
    ports:
     - "${PORT}:8000"
    env_file: .env.review
    volumes:
      - ../:/app

  postgres:
    image: mdillon/postgis:10
    volumes:
      - ./data/pg/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env.review
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always

  geoserver:
    image: winsent/geoserver:2.13
    ports:
      - 81:8080
    volumes:
      - ./data/geoserver/:/opt/geoserver/data_dir
