# Generated by Django 2.0.7 on 2019-02-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_renter', models.IntegerField()),
                ('subject', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('house', models.CharField(blank=True, max_length=4, null=True)),
                ('housing', models.CharField(blank=True, max_length=3, null=True)),
                ('building', models.CharField(blank=True, max_length=2, null=True)),
                ('office', models.CharField(blank=True, max_length=3, null=True)),
                ('telephon', models.CharField(blank=True, max_length=16, null=True)),
                ('type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', models.TextField(blank=True, null=True)),
                ('num_kvr', models.CharField(blank=True, max_length=4, null=True)),
                ('num_vyd', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'allotment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictForestry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_df', models.IntegerField(blank=True, null=True)),
                ('name_df', models.CharField(blank=True, max_length=80, null=True)),
                ('code_f', models.IntegerField(blank=True, null=True)),
                ('name_f', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'district_forestry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fid', models.BigIntegerField(blank=True, null=True)),
                ('subject', models.IntegerField(blank=True, null=True)),
                ('org_name', models.CharField(blank=True, max_length=80, null=True)),
                ('num_doc', models.CharField(blank=True, max_length=50, null=True)),
                ('forestry', models.CharField(blank=True, max_length=80, null=True)),
                ('district_forestry', models.CharField(blank=True, max_length=80, null=True)),
                ('uroch', models.CharField(blank=True, max_length=80, null=True)),
                ('num_kv', models.TextField(blank=True, null=True)),
                ('num_allot', models.TextField(blank=True, null=True)),
                ('num_fca', models.CharField(blank=True, max_length=50, null=True)),
                ('ar_fca', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('fell_form', models.TextField(blank=True, null=True)),
                ('fell_type', models.IntegerField(blank=True, null=True)),
                ('main_type', models.IntegerField(blank=True, null=True)),
                ('sortiment', models.IntegerField(blank=True, null=True)),
                ('vol_zag', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('biz_type', models.CharField(blank=True, max_length=50, null=True)),
                ('expl_ar', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('cel_nazn', models.IntegerField(blank=True, null=True)),
                ('cat_zas', models.IntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('video_cat', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FcaOld',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('num_fca', models.CharField(blank=True, max_length=50, null=True)),
                ('num_doc', models.CharField(blank=True, max_length=50, null=True)),
                ('uroch', models.CharField(blank=True, max_length=50, null=True)),
                ('main_type', models.IntegerField(blank=True, null=True)),
                ('fell_form', models.TextField(blank=True, null=True)),
                ('fell_type', models.IntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('fid', models.BigIntegerField(blank=True, null=True)),
                ('org_name', models.CharField(blank=True, max_length=50, null=True)),
                ('forestry', models.CharField(blank=True, max_length=80, null=True)),
                ('district_forestry', models.CharField(blank=True, max_length=50, null=True)),
                ('num_kv', models.TextField(blank=True, null=True)),
                ('num_allot', models.TextField(blank=True, null=True)),
                ('biz_type', models.CharField(blank=True, max_length=20, null=True)),
                ('ar_fca', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('cel_nazn', models.IntegerField(blank=True, null=True)),
                ('cat_zas', models.IntegerField(blank=True, null=True)),
                ('expl_ar', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'fca_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FcaPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_no', models.IntegerField(blank=True, null=True)),
                ('coords', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_no', models.IntegerField(blank=True, null=True)),
                ('ext', models.CharField(blank=True, max_length=10, null=True)),
                ('ref', models.TextField(blank=True, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fca_photo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FcaUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fell_form', models.TextField(blank=True, null=True)),
                ('fell_type', models.SmallIntegerField(blank=True, null=True)),
                ('main_type', models.SmallIntegerField(blank=True, null=True)),
                ('kind', models.SmallIntegerField(blank=True, null=True)),
                ('ed_izm', models.TextField(blank=True, null=True)),
                ('vol_drew', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('fca_res', models.SmallIntegerField(blank=True, null=True)),
                ('vol_res', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'fca_use',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FcaWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkod', models.SmallIntegerField(blank=True, null=True)),
                ('main_type', models.SmallIntegerField(blank=True, null=True)),
                ('fell_form', models.TextField(blank=True, null=True)),
                ('fell_type', models.SmallIntegerField(blank=True, null=True)),
                ('kind', models.SmallIntegerField(blank=True, null=True)),
                ('sortiment', models.SmallIntegerField(blank=True, null=True)),
                ('vol_drew', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('use_type', models.SmallIntegerField(blank=True, null=True)),
                ('fca_res', models.SmallIntegerField(blank=True, null=True)),
                ('ed_izm', models.TextField(blank=True, null=True)),
                ('vol_les', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('act_name', models.SmallIntegerField(blank=True, null=True)),
                ('obj_type', models.SmallIntegerField(blank=True, null=True)),
                ('use_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('indicator', models.SmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_report', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fca_works',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FcPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fc_points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForestActivity',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('activity', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'forest_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForestCutting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('geom', models.TextField(blank=True, null=True)),
                ('num_fca', models.CharField(blank=True, max_length=10, null=True)),
                ('type_resou', models.BigIntegerField(blank=True, null=True)),
                ('ed_izm', models.CharField(blank=True, max_length=254, null=True)),
                ('seizure_vo', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'forest_cutting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForestDeclaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_decl', models.CharField(blank=True, max_length=3, null=True)),
                ('date_decl', models.DateField(blank=True, null=True)),
                ('use_forest', models.IntegerField(blank=True, null=True)),
                ('govsub', models.CharField(blank=True, max_length=150, null=True)),
                ('name_doc', models.CharField(blank=True, max_length=30, null=True)),
                ('num_doc', models.CharField(blank=True, max_length=10, null=True)),
                ('date_doc', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'forest_declaration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForestKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'forest_kind',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForestObjtype',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('obj_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'forest_objtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForestProperties',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uroch', models.CharField(blank=True, max_length=20, null=True)),
                ('area_felling', models.FloatField(blank=True, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('vol_forest', models.FloatField(blank=True, null=True)),
                ('vol_biz', models.FloatField(blank=True, null=True)),
                ('vol_plan', models.FloatField(blank=True, null=True)),
                ('date_report', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'forest_properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForestProtection',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('protect_cat', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'forest_protection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForestPurpose',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('purpose', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'forest_purpose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForestResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=110, null=True)),
            ],
            options={
                'db_table': 'forest_resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForestSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_doc', models.CharField(blank=True, max_length=80, null=True)),
                ('date_doc', models.DateField(blank=True, null=True)),
                ('id_renter', models.IntegerField(blank=True, null=True)),
                ('name_gov', models.CharField(blank=True, max_length=80, null=True)),
                ('num_grd', models.CharField(blank=True, max_length=80, null=True)),
                ('date_grd', models.DateField(blank=True, null=True)),
                ('kud_number', models.CharField(blank=True, max_length=30, null=True)),
                ('num_glr', models.CharField(blank=True, max_length=30, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_stop', models.DateField(blank=True, null=True)),
                ('num_akt', models.CharField(blank=True, max_length=15, null=True)),
                ('date_akt', models.DateField(blank=True, null=True)),
                ('projects', models.IntegerField(blank=True, null=True)),
                ('num_kv', models.CharField(blank=True, max_length=10, null=True)),
                ('district_forestry', models.CharField(blank=True, max_length=50, null=True)),
                ('forestry', models.CharField(blank=True, max_length=80, null=True)),
                ('radio', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'forest_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForestSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'forest_sort',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForestUse',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'forest_use',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForestWorks',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'forest_works',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndEntrep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org_prav_form', models.TextField()),
                ('inn', models.CharField(max_length=12)),
                ('account_name', models.CharField(max_length=20)),
                ('acc_pwd', models.CharField(blank=True, max_length=128, null=True)),
                ('second_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('patronymic', models.CharField(max_length=40)),
                ('identity_doc', models.CharField(max_length=40)),
                ('serial_doc', models.CharField(max_length=8)),
                ('number_doc', models.CharField(max_length=8)),
                ('ogrnip', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'ind_entrep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegalDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'legal_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_name', models.CharField(blank=True, max_length=80, null=True)),
                ('obj_num', models.IntegerField(blank=True, null=True)),
                ('obj_infr', models.CharField(blank=True, max_length=80, null=True)),
                ('obj_area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'objects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org_prav_form', models.TextField()),
                ('inn', models.CharField(max_length=12)),
                ('account_name', models.CharField(max_length=20)),
                ('acc_pwd', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('snameplp', models.CharField(blank=True, max_length=80, null=True)),
                ('fnameplp', models.CharField(blank=True, max_length=80, null=True)),
                ('patronymicplp', models.CharField(blank=True, max_length=80, null=True)),
                ('position', models.CharField(blank=True, max_length=80, null=True)),
                ('ogrn', models.CharField(blank=True, max_length=13, null=True)),
                ('identity_doc', models.CharField(blank=True, max_length=40, null=True)),
                ('serial_doc', models.CharField(blank=True, max_length=8, null=True)),
                ('number_doc', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'organizations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Osnovanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'osnovanie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org_prav_form', models.TextField()),
                ('inn', models.CharField(max_length=12)),
                ('account_name', models.CharField(max_length=20)),
                ('acc_pwd', models.CharField(blank=True, max_length=128, null=True)),
                ('second_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('patronymic', models.CharField(max_length=40)),
                ('identity_doc', models.CharField(max_length=40)),
                ('serial_doc', models.CharField(max_length=8)),
                ('number_doc', models.CharField(max_length=8)),
                ('ogrnip', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'persons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.IntegerField(blank=True, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'photo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_renter', models.BigIntegerField(blank=True, null=True)),
                ('num_proj', models.CharField(blank=True, max_length=80, null=True)),
                ('date_project', models.DateField(blank=True, null=True)),
                ('date_zakl', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quarters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', models.TextField(blank=True, null=True)),
                ('forest_code', models.CharField(blank=True, max_length=10, null=True)),
                ('forest_name', models.CharField(blank=True, max_length=20, null=True)),
                ('quarter', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quarters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuartersTest',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('id_df', models.SmallIntegerField()),
                ('num_kv', models.SmallIntegerField(blank=True, null=True)),
                ('descr', models.CharField(blank=True, max_length=254, null=True)),
                ('kod', models.SmallIntegerField(blank=True, null=True)),
                ('kod1', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quarters_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Renters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_prav_form', models.TextField()),
                ('inn', models.CharField(max_length=12)),
                ('account_name', models.CharField(max_length=20, unique=True)),
                ('acc_pwd', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'renters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeFelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'type_felling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypesForestry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'types_forestry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viddoc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'viddoc',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='forestation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='imagetest',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pwdtest',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subjectrf',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vltest',
            options={'managed': False},
        ),
    ]
