# Generated by Django 2.0.7 on 2019-02-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igt', '0002_auto_20190213_0804'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forestation',
            table='forestation',
        ),
        migrations.AlterModelTable(
            name='imagetest',
            table='image_test',
        ),
        migrations.AlterModelTable(
            name='pwdtest',
            table='pwd_test',
        ),
        migrations.AlterModelTable(
            name='subjectrf',
            table='subject_rf',
        ),
        migrations.AlterModelTable(
            name='vltest',
            table='vl_test',
        ),
    ]
