# Generated by Django 2.0.7 on 2019-02-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('house', models.CharField(blank=True, max_length=4, null=True)),
                ('housing', models.CharField(blank=True, max_length=3, null=True)),
                ('building', models.CharField(blank=True, max_length=2, null=True)),
                ('office', models.CharField(blank=True, max_length=3, null=True)),
                ('telephon', models.CharField(blank=True, max_length=16, null=True)),
                ('type', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'verbose_name': 'адрес',
                'verbose_name_plural': 'список адресов',
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='дата утверждения')),
                ('organ', models.CharField(help_text='наименование органа государственной власти, органа местного самоуправления', max_length=80)),
                ('num', models.CharField(help_text='номер государственной регистрации документа', max_length=80, verbose_name='номер регистрации')),
                ('date_reg', models.DateField(null=True, verbose_name='дата регистрации')),
                ('kadastre', models.CharField(max_length=30, verbose_name='кадастровый номер')),
                ('glr', models.CharField(help_text='номер учетной записи в государственном лесном реестре (ГЛР)', max_length=30, verbose_name='номер ГЛР')),
                ('use_start', models.DateField(verbose_name='начало использования')),
                ('use_end', models.DateField(verbose_name='конец использования')),
                ('act_num', models.CharField(help_text='номер акта приема-передачи лесного участка', max_length=15, verbose_name='номер акта')),
                ('act_date', models.DateField(help_text='дата акта приема-передачи лесного участка', verbose_name='дата акта')),
                ('project', models.BooleanField(verbose_name='Есть проект освоения?')),
                ('project_date', models.DateField(help_text='cрок действия проекта освоения лесов', verbose_name='срок действия проекта')),
                ('project_author', models.CharField(help_text='разработчик проекта освоения лесов', max_length=80, verbose_name='автор проекта')),
                ('positive_date', models.DateField(help_text='дата выдачи положительного заключения по итогам государственной экспертизы проекта освоения лесов', verbose_name='дата позитивчика')),
                ('reas_doc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.Osnovanie', verbose_name='основание')),
            ],
            options={
                'verbose_name': 'договор',
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.CreateModel(
            name='Renters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inn', models.CharField(max_length=12)),
                ('account_name', models.CharField(max_length=20)),
                ('acc_pwd', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('snameplp', models.CharField(blank=True, max_length=80, null=True)),
                ('fnameplp', models.CharField(blank=True, max_length=80, null=True)),
                ('patronymicplp', models.CharField(blank=True, max_length=80, null=True)),
                ('position', models.CharField(blank=True, max_length=80, null=True)),
                ('ogrn', models.CharField(blank=True, max_length=13, null=True)),
                ('serial_doc', models.CharField(blank=True, max_length=8, null=True)),
                ('number_doc', models.CharField(blank=True, max_length=8, null=True)),
                ('identity_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.IdentDoc')),
                ('leg_docum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.LegalDocuments')),
                ('org_prav_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.Pravform')),
            ],
            options={
                'managed': True,
                'verbose_name': 'арендатор',
                'verbose_name_plural': 'арендаторы',
            },
        ),
        migrations.AddField(
            model_name='agreement',
            name='renters_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='renter.Renters', verbose_name='рентер'),
        ),
    ]
