# Generated by Django 2.0.7 on 2019-02-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renters',
            name='fnameplp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='renters',
            name='identity_doc',
            field=models.ForeignKey(blank=True, help_text='документ удостоверяющий личность', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.IdentDoc'),
        ),
        migrations.AlterField(
            model_name='renters',
            name='inn',
            field=models.CharField(max_length=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='renters',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='renters',
            name='number_doc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='номер документа'),
        ),
        migrations.AlterField(
            model_name='renters',
            name='ogrn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='renters',
            name='patronymicplp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='renters',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='renters',
            name='serial_doc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='серия документа'),
        ),
        migrations.AlterField(
            model_name='renters',
            name='snameplp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
