# Generated by Django 2.0.7 on 2019-02-19 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification_list', '0004_auto_20190219_1154'),
        ('renter', '0002_auto_20190219_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentAddres',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('house', models.CharField(blank=True, max_length=4, null=True)),
                ('housing', models.CharField(blank=True, max_length=3, null=True)),
                ('building', models.CharField(blank=True, max_length=2, null=True)),
                ('office', models.CharField(blank=True, max_length=3, null=True)),
                ('telephon', models.CharField(blank=True, max_length=16, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('renters_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='renter.Renters', verbose_name='рентер')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.SubjectRf')),
            ],
            options={
                'verbose_name_plural': 'список адресов',
                'managed': True,
                'verbose_name': 'адрес',
            },
        ),
    ]
