# Generated by Django 2.0.7 on 2019-02-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification_list', '0005_auto_20190220_1523'),
        ('renter', '0003_rentaddres'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='viddoc',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='classification_list.Viddoc', verbose_name='viddoc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='renters',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наиминование организации'),
        ),
    ]
