# Generated by Django 2.0.7 on 2019-03-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0004_auto_20190220_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renters',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='renters',
            name='inn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН'),
        ),
    ]
