# Generated by Django 2.0.7 on 2019-02-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForestActivity',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('activity', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Forestation',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('indicator', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'лесовостановление',
            },
        ),
        migrations.CreateModel(
            name='ForestKind',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'видовой состав',
            },
        ),
        migrations.CreateModel(
            name='ForestObjtype',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('obj_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'объект',
                'verbose_name_plural': 'объекты',
            },
        ),
        migrations.CreateModel(
            name='ForestProtection',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('protect_cat', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'категория лесозащиты',
            },
        ),
        migrations.CreateModel(
            name='ForestPurpose',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('purpose', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'целевое назначения',
            },
        ),
        migrations.CreateModel(
            name='ForestResource',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=110, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'ресурсы',
            },
        ),
        migrations.CreateModel(
            name='ForestSort',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'сортиментный с-в',
            },
        ),
        migrations.CreateModel(
            name='ForestUse',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'использование лесов',
            },
        ),
        migrations.CreateModel(
            name='ForestWorks',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'лесные работы',
            },
        ),
        migrations.CreateModel(
            name='IdentDoc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ident_doc', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'документ удоств. личности',
            },
        ),
        migrations.CreateModel(
            name='LegalDocuments',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'документ',
            },
        ),
        migrations.CreateModel(
            name='Osnovanie',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'основание',
            },
        ),
        migrations.CreateModel(
            name='Pravform',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prav_form', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'правовая форма',
            },
        ),
        migrations.CreateModel(
            name='PwdTest',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('acc_name', models.CharField(blank=True, max_length=20, null=True)),
                ('pwd_hash', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'генка??',
            },
        ),
        migrations.CreateModel(
            name='Quarters',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('geom', models.TextField(blank=True, null=True)),
                ('forest_code', models.CharField(blank=True, max_length=10, null=True)),
                ('forest_name', models.CharField(blank=True, max_length=20, null=True)),
                ('quarter', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShapeFelling',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'форма рубки',
            },
        ),
        migrations.CreateModel(
            name='SubjectRf',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('kod_okato', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'субъект РФ',
                'verbose_name_plural': 'субъекты РФ',
            },
        ),
        migrations.CreateModel(
            name='TypeFelling',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'вид рубки',
            },
        ),
        migrations.CreateModel(
            name='TypesForestry',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'тип хозяйства',
            },
        ),
        migrations.CreateModel(
            name='UnitMeas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('qart_names', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Viddoc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name': 'вид раз. документации',
            },
        ),
    ]
