# Generated by Django 2.0.7 on 2019-02-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification_list', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PwdTest',
        ),
        migrations.RemoveField(
            model_name='forestactivity',
            name='activity',
        ),
        migrations.AddField(
            model_name='forestactivity',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
