# Generated by Django 2.0.7 on 2019-02-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification_list', '0002_auto_20190218_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forestpurpose',
            options={'managed': True, 'verbose_name': 'целевое назначение'},
        ),
        migrations.RenameField(
            model_name='forestobjtype',
            old_name='obj_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='forestprotection',
            old_name='protect_cat',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='forestresource',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quarters',
            old_name='forest_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='forestation',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='forestpurpose',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='identdoc',
            name='ident_doc',
        ),
        migrations.RemoveField(
            model_name='pravform',
            name='prav_form',
        ),
        migrations.RemoveField(
            model_name='unitmeas',
            name='qart_names',
        ),
        migrations.RemoveField(
            model_name='viddoc',
            name='type',
        ),
        migrations.AddField(
            model_name='forestation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forestpurpose',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='identdoc',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pravform',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unitmeas',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='viddoc',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forestuse',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forestworks',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
