# Generated by Django 2.0.7 on 2019-02-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification_list', '0003_auto_20190218_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identdoc',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='документ, удостоверяющий личность'),
        ),
    ]
