# Generated by Django 2.0.7 on 2019-02-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification_list', '0004_auto_20190219_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quarters',
        ),
        migrations.AlterModelOptions(
            name='forestactivity',
            options={'managed': True, 'verbose_name': 'мероприятия', 'verbose_name_plural': 'мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='forestation',
            options={'managed': True, 'verbose_name': 'лесовостановление', 'verbose_name_plural': 'лесовостановление'},
        ),
        migrations.AlterModelOptions(
            name='forestkind',
            options={'managed': True, 'verbose_name': 'видовой состав', 'verbose_name_plural': 'видовой состав'},
        ),
        migrations.AlterModelOptions(
            name='forestprotection',
            options={'managed': True, 'verbose_name': 'категория лесозащиты', 'verbose_name_plural': 'категории лесозащиты'},
        ),
        migrations.AlterModelOptions(
            name='forestpurpose',
            options={'managed': True, 'verbose_name': 'целевое назначение', 'verbose_name_plural': 'целевое назначение'},
        ),
        migrations.AlterModelOptions(
            name='forestresource',
            options={'managed': True, 'verbose_name': 'ресурс', 'verbose_name_plural': 'ресурсы'},
        ),
        migrations.AlterModelOptions(
            name='forestsort',
            options={'managed': True, 'verbose_name': 'сортиментный с-в', 'verbose_name_plural': 'сортиментный с-в'},
        ),
        migrations.AlterModelOptions(
            name='forestuse',
            options={'managed': True, 'verbose_name': 'использование лесов', 'verbose_name_plural': 'виды использования лесов'},
        ),
        migrations.AlterModelOptions(
            name='forestworks',
            options={'managed': True, 'verbose_name': 'лесные работы', 'verbose_name_plural': 'лесные работы'},
        ),
        migrations.AlterModelOptions(
            name='identdoc',
            options={'managed': True, 'verbose_name': 'документ удоств. личности', 'verbose_name_plural': 'виды документов удос. личн.'},
        ),
        migrations.AlterModelOptions(
            name='legaldocuments',
            options={'managed': True, 'verbose_name': 'документ', 'verbose_name_plural': 'документы'},
        ),
        migrations.AlterModelOptions(
            name='osnovanie',
            options={'managed': True, 'verbose_name': 'основание', 'verbose_name_plural': 'основание'},
        ),
        migrations.AlterModelOptions(
            name='pravform',
            options={'managed': True, 'verbose_name': 'правовая форма', 'verbose_name_plural': 'правовые формы'},
        ),
        migrations.AlterModelOptions(
            name='shapefelling',
            options={'managed': True, 'verbose_name': 'форма рубки', 'verbose_name_plural': 'формы рубки'},
        ),
        migrations.AlterModelOptions(
            name='typefelling',
            options={'managed': True, 'verbose_name': 'вид рубки', 'verbose_name_plural': 'виды рубки'},
        ),
        migrations.AlterModelOptions(
            name='typesforestry',
            options={'managed': True, 'verbose_name': 'тип хозяйства', 'verbose_name_plural': 'типы хозяйства'},
        ),
        migrations.AlterModelOptions(
            name='unitmeas',
            options={'managed': True, 'verbose_name': 'единицы измерения', 'verbose_name_plural': 'единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='viddoc',
            options={'managed': True, 'verbose_name': 'вид раз. документации', 'verbose_name_plural': 'виды раз. документации'},
        ),
    ]
