# Generated by Django 2.0.7 on 2019-02-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification_list', '0005_auto_20190220_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestactivity',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forestkind',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectrf',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
