# Generated by Django 2.0.7 on 2019-02-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification_list', '0006_auto_20190225_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestpurpose',
            name='name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
