# Generated by Django 2.0.7 on 2019-02-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification_list', '0007_auto_20190225_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shapefelling',
            options={'managed': True, 'verbose_name': 'вид рубки', 'verbose_name_plural': 'виды рубки'},
        ),
        migrations.AlterModelOptions(
            name='typefelling',
            options={'managed': True, 'verbose_name': 'форма рубки', 'verbose_name_plural': 'формы рубки'},
        ),
    ]
